//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9164
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.2.123.20110")]
[assembly: global::System.Reflection.AssemblyCopyrightAttribute("Copyright © PKUICL 2010")]
[assembly: global::System.Reflection.AssemblyCompanyAttribute("PKUICL")]
[assembly: global::System.Reflection.AssemblyProductAttribute("Sim2DClt")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("Sim2DClt")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="URWPGSim2D.Sim2DClt.Y2010.M11, Version=1.2.123.20110, Culture=neutral, PublicKeyT" +
    "oken=04f000b8db128100")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.AllowPartiallyTrustedCallersAttribute()]

namespace Dss.Transforms.TransformURWPGSim2D {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::URWPGSim2D.Sim2DClt.Proxy.Sim2DCltState), new global::Microsoft.Dss.Core.Attributes.Transform(URWPGSim2D_Sim2DClt_Proxy_Sim2DCltState_TO_URWPGSim2D_Sim2DClt_Sim2DCltState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::URWPGSim2D.Sim2DClt.Sim2DCltState), new global::Microsoft.Dss.Core.Attributes.Transform(URWPGSim2D_Sim2DClt_Sim2DCltState_TO_URWPGSim2D_Sim2DClt_Proxy_Sim2DCltState));
        }
        
        private static global::URWPGSim2D.Sim2DClt.Proxy.Sim2DCltState _cachedInstance0 = new global::URWPGSim2D.Sim2DClt.Proxy.Sim2DCltState();
        
        private static global::URWPGSim2D.Sim2DClt.Sim2DCltState _cachedInstance = new global::URWPGSim2D.Sim2DClt.Sim2DCltState();
        
        public static object URWPGSim2D_Sim2DClt_Proxy_Sim2DCltState_TO_URWPGSim2D_Sim2DClt_Sim2DCltState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object URWPGSim2D_Sim2DClt_Sim2DCltState_TO_URWPGSim2D_Sim2DClt_Proxy_Sim2DCltState(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
